from typing import Any
from simple_quantum_network_simulator.address import QNodeAddress


class Packet:
    """A classical packet that can be sent over a Link."""

    prev_hop: QNodeAddress | None
    """The address of the QNode or QNic that sent this packet.
    if this is None, then the packet is being generated by the QNode itself."""

    data: Any

    def __init__(self, data: Any, prev_hop: QNodeAddress | None = None) -> None:
        self.prev_hop = prev_hop
        self.data = data

    def __repr__(self) -> str:
        return f"Packet({self.data})"
